/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.rivaldy.mvnfirst;

import com.mycompany.mavenappdesktop.LatestConversion;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import org.springframework.web.client.RestTemplate;

/**
 *
 * @author RomyRivaldy
 */
public class ExchangeApplication extends javax.swing.JFrame {

    Currency sourceCurrency;
    Currency targetCurrency;
LatestConversion latest;
    /**
     * Creates new form ExchangeApplication
     */
    public ExchangeApplication() {
        getComboboxData();
        initComponents();
        getCurrenciesConvertInWorld();
    }
    private DefaultComboBoxModel getComboboxData(){
        List<Currency> curList = toList();
        return new DefaultComboBoxModel(curList.toArray());
    }
    private List<Currency> toList(){
        List<Currency> curList = new ArrayList<Currency>();
        Map<String, String> curMap = getCurrencyFromWebServices();
        Set<String> keys = curMap.keySet();
        for (String key : keys) {
            curList.add(new Currency(key, curMap.get(key)));
        }
        return curList;
    }
    private Map<String, String> getCurrencyFromWebServices(){
        RestTemplate restTemplate = new RestTemplate();
        Map<String, String> curMap = restTemplate.getForObject("https://openexchangerates.org/api/currencies.json", Map.class);
        return curMap;
    }
    
     private String getUangDari(String froms){
        String[]data = froms.split("-");
        String from = data[0];
        return from;
    }
    
    private String getUangKe(String froms){
        String[]data = froms.split("-");
        String from = data[0];
        return from;
    }
    
    private void getCurrenciesConvertInWorld(){
        String url = "https://openexchangerates.org/api/latest.json?app_id=9971e55b38854948a88c9d1cb6814cc6";
        RestTemplate restTemplate = new RestTemplate();
        latest = restTemplate.getForObject(url, LatestConversion.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fromCombobox = new javax.swing.JComboBox<>();
        toCombobox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        uangtxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        hasiltxt = new javax.swing.JTextField();
        updateLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("From Currency");

        jLabel2.setText("To Currency");

        fromCombobox.setModel(getComboboxData());
        fromCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromComboboxActionPerformed(evt);
            }
        });

        toCombobox.setModel(getComboboxData());
        toCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toComboboxActionPerformed(evt);
            }
        });

        jLabel3.setText("Total");

        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        updateLabel.setText("Update: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(updateLabel)
                    .addComponent(uangtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(hasiltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(toCombobox, javax.swing.GroupLayout.Alignment.LEADING, 0, 170, Short.MAX_VALUE)
                        .addComponent(fromCombobox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fromCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(uangtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hasiltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateLabel)
                .addGap(68, 68, 68))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromComboboxActionPerformed
        // TODO add your handling code here:
        JComboBox fromCB = (JComboBox) evt.getSource();
        sourceCurrency = (Currency) fromCB.getSelectedItem();
//        System.out.println("Source Currency : "+sourceCurrency);
    }//GEN-LAST:event_fromComboboxActionPerformed

    private void toComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toComboboxActionPerformed
        // TODO add your handling code here:
        JComboBox toCB = (JComboBox) evt.getSource();
        targetCurrency = (Currency) toCB.getSelectedItem();
//        System.out.println("Target Currency : "+targetCurrency);
    }//GEN-LAST:event_toComboboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String from = getUangDari(fromCombobox.getSelectedItem().toString());
        String ke = getUangKe(toCombobox.getSelectedItem().toString());
        Double uang = Double.parseDouble(uangtxt.getText());
        Double hasil = latest.getConvertionResult(from, ke, uang);
        String fmt = String.format(ke + " %,.2f", hasil);
        hasiltxt.setText(fmt);
        updateLabel.setText("Updates On: " + latest.getLastDate());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExchangeApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExchangeApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExchangeApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExchangeApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExchangeApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> fromCombobox;
    private javax.swing.JTextField hasiltxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> toCombobox;
    private javax.swing.JTextField uangtxt;
    private javax.swing.JLabel updateLabel;
    // End of variables declaration//GEN-END:variables
}
